# common.py
import os
import subprocess
import librosa
import soundfile as sf
import numpy as np
from pytubefix import YouTube

def download_audio(youtube_url, output_path):
    try:
        yt = YouTube(youtube_url)
        video_title = yt.title
        download_folder = os.path.join(output_path, video_title)
        os.makedirs(download_folder, exist_ok=True)

        mp3_file = os.path.join(download_folder, f"{video_title}.mp3")
        if os.path.exists(mp3_file):
            print(f"Audio file '{mp3_file}' already exists. Skipping download.")
            return mp3_file, download_folder

        audio_stream = yt.streams.filter(only_audio=True).first()
        audio_file = audio_stream.download(output_path=download_folder)
        base, ext = os.path.splitext(audio_file)
        os.rename(audio_file, mp3_file)
        return mp3_file, download_folder
    except Exception as e:
        raise RuntimeError(f"Failed to download audio: {str(e)}")

def pitch_shift(audio_file, semitones, output_folder):
    try:
        shifted_file = os.path.join(output_folder, f"{os.path.splitext(os.path.basename(audio_file))[0]}_{semitones:+}st.mp3")
        if os.path.exists(shifted_file):
            print(f"Pitch-shifted file '{shifted_file}' already exists. Skipping.")
            return shifted_file

        y, sr = librosa.load(audio_file, sr=None)
        y_shifted = librosa.effects.pitch_shift(y, sr=sr, n_steps=semitones)  # Corrected the function call
        sf.write(shifted_file, y_shifted, sr)
        return shifted_file
    except Exception as e:
        raise RuntimeError(f"Pitch shifting failed: {str(e)}")

def separate_stems(audio_file, model, output_folder):
    try:
        stems_output = os.path.join(output_folder, 'stems')
        output_model_path = os.path.join(stems_output, model)
        
        if os.path.exists(output_model_path):
            print(f"Stems generated by model at '{output_model_path}' already exists. Skipping.")
            return stems_output

        if not os.path.exists(stems_output):
            os.makedirs(stems_output)

        subprocess.run(['demucs', '-n', model, '--mp3', '-o', stems_output, audio_file], check=True)
        return stems_output
    except subprocess.CalledProcessError as e:
        raise RuntimeError(f"Stem separation failed: {str(e)}")

def create_beat_track(audio_file, output_folder):
    try:
        beat_track_file = os.path.join(output_folder, f"{os.path.splitext(os.path.basename(audio_file))[0]}_beat_track.mp3")
        beat_track_file_mixed = os.path.join(output_folder, f"{os.path.splitext(os.path.basename(audio_file))[0]}_beat_track_mixed.mp3")
        if os.path.exists(beat_track_file):
            print(f"Beat track '{beat_track_file}' already exists. Skipping.")
            return beat_track_file

        # Load audio file
        y, sr = librosa.load(audio_file, sr=None)

        # Detect beat frames
        tempo, beat_frames = librosa.beat.beat_track(y=y, sr=sr)
        print(f"Detected tempo: {tempo}")

        # Create a click track
        click_audio = librosa.clicks(frames=beat_frames, sr=sr, length=len(y))

        # Mix the original audio with the click track
        mixed_audio = y + click_audio

        # Save the standalone beat track
        sf.write(beat_track_file, click_audio, sr)
        # Save the beat track
        sf.write(beat_track_file_mixed, mixed_audio, sr)
        return beat_track_file
    except Exception as e:
        raise RuntimeError(f"Creating beat track failed: {str(e)}")
